stages:
    - build
    - test

build:
    stage: build
    image: node:12
    script:
        - npm install
        - npm install -g @angular/cli
        - ng build
    cache:
        paths:
            - ./node_modules
    artifacts:
        expire_in: 1 hour
        paths:
            - dist/my-app
    only:
        - master
test:
    stage: test
    image: circleci/node:12-browsers
    script:
        - npm install
        - sudo npm install -g @angular/cli
        - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
    cache:
        paths:
            - ./node_modules
    only:
        - master